### ISSUE TITLE
Java examples no longer work

### ISSUE THREAD

**Issue by brikis98** [brikis98/ping-play#13]
Java controllers no longer work in this app after the upgrade to Play 2.4. This has nothing to do with the streaming code (even a simple `return ok("hi")` controller won't work), but rather, something to do with using the Scala compile time dependency injection with a Java controller. I've asked a [question on the Play mailing list](https://groups.google.com/forum/#!topic/play-framework/A0rCbXVX_Gw) to try to track this one down. Until it's resolved, visiting the URL for the Java example will show the following error:

```
[error] p.c.s.n.PlayDefaultUpstreamHandler - Exception caught in Netty
scala.MatchError: Right((play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3@43355ebf,play.api.DefaultApplication@2ac109ad)) (of class scala.util.Right)
    at play.core.server.netty.PlayDefaultUpstreamHandler.messageReceived(PlayDefaultUpstreamHandler.scala:150) ~[play-netty-server_2.11-2.4.0.jar:2.4.0]
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.3.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.3.Final.jar:na]
     at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.3.Final.jar:na]
        at com.typesafe.netty.http.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:62) [netty-http-pipelining-1.1.4.jar:na]
 at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.10.3.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.3.Final.jar:na]
     at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.3.Final.jar:na]
        at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108) [netty-3.10.3.Final.jar:na]
       at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.3.Final.jar:na]
```

**Comment by brikis98** [comment]
Split the sample apps into Java and Scala versions to work around this.

**Comment by mantsak** [comment]
I'm following your changes and learning a lot. Fantastic work, the code is soo clean.

I might have an idea regarding error handling and the problem that headers are already sent. The header (and footer) itself could also be a Pagelet. If one important service call fails, another responce can be given (404, 301/302). This requires a little bit more waiting time and a combination of "important" Pagelets with fromSequentialPagelets and JavaScript driven fromInterleavedPagelets. This adds waiting time to the first byte, of course.

**Comment by brikis98** [comment]
@mantsak: Thanks!
 
I think if there is data that is absolutely critical and you want to wait for it before sending back headers, you would structure the controller code like this:

```scala
def index = Action.async {
  val dataFuture1 = makeServiceCall()
  val dataFuture2 = makeServiceCall()
  val criticalDataFuture = makeServiceCall()

  val pagelet1 = Pagelet.fromHtmlFuture(dataFuture1)
  val pagelet2 = Pagelet.fromHtmlFuture(dataFuture2)

  val body = HtmlStream.fromInterleavedPagelets(pagelet1, pagelet2)

  for {
    criticalData <- criticalDataFuture
  } yield {
    Ok.chunked(views.stream.myTemplate(criticalData, body))
  }
}
```

In other words, data that you must wait for you treat as a normal `Future` and only send back a response after it has redeemed. The rest of the data, you shove into an `HtmlStream` (i.e. an `Enumerator`) and allow it stream down whenever the data comes back, or even if there is an error. In fact, I added an example of how to handle errors while streaming in the sample apps. Check out `controllers.MoreBigPipeExamples#errorHandling`.
